GET http://localhost:3000/Utilisateur


###

POST  http://localhost:3000/Utilisateur
Content-Type: application/json
{
    "nom_de_famille": "Jean",
    "email": "jean@gmail.com",
    "mot_de_passe": "JeanJean"
}
###